### Example 1
FROM naveensingla17/webserver:webserver_v1.3

LABEL maintainer="naveen.singla17@gmail.com"
LABEL version="2.1"
LABEL


### Example 2
ARG osver=8

FROM centos:$osver

ARG dirname=/myapp
ARG gname=tgindia
ARG uname=ekamjeet
ARG myappport=8000

LABEL maintainer="Ekamjeet singh"

RUN groupadd $gname && \
    useradd -m -G $gname $uname && \
    mkdir -p $dirname && \
    chown $uname:$gname  $dirname

EXPOSE $myappport

CMD ["sh", "-c", "echo Welcome $uname your groupname is $gname and port number is $myappport"]


### Example 3

### Example 4

### Example 5

### Example 6

